version: '3.8'

services:
  app:
    build:
      context: laravel
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ai
      DB_USERNAME: chad
      DB_PASSWORD: 0000

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: chad
      POSTGRES_DB: ai
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U chad -d ai -c 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
